[package]
name = "widget_gallery"
version = "0.1.0"
edition = "2021"

[dependencies]
vizia = {path = "../../../vizia"}
fern = "0.6.2"
log = "0.4.19"
chrono = "0.4.34"

[profile.dev.package."*"]
opt-level = 3