[package]
name = "vizia_window"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "The window components of vizia"
rust-version = "1.60"

[dependencies]
vizia_input = { path = "../vizia_input" }
vizia_style = { path = "../vizia_style" }
# morphorm = {path = "../../../morphorm" }
morphorm = "0.6.4"
accesskit = "0.11.0"
#morphorm = { path = "../../../morphorm", features = ["rounding"] }
