[package]
name = "vizia_storage"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "The storage data structures of vizia"
rust-version = "1.60"

[dependencies]
vizia_id = { path = "../vizia_id" }

# morphorm = {path = "../../../morphorm" }
morphorm = "0.6.4"
#morphorm = { path = "../../../morphorm", features = ["rounding"] }
