[package]
name = "vizia_storage"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "The storage data structures of vizia"
rust-version = "1.60"

[dependencies]
vizia_id = { path = "../vizia_id" }

morphorm = {path = "../../../morphorm" }
# morphorm = {git = "https://github.com/vizia/morphorm", rev = "fe7c4632b7f08e29bf36ffad2bf0ce45ce049fbf" }
#morphorm = { path = "../../../morphorm", features = ["rounding"] }
